<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
		<DocumentationFile>GrillBot.Common.xml</DocumentationFile>
		<NoWarn>1701;1702;1591</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
		<DocumentationFile>GrillBot.Common.xml</DocumentationFile>
		<NoWarn>1701;1702;1591</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Identity" />
		<PackageReference Include="Discord.Net" />
		<PackageReference Include="Humanizer.Core.cs" />
		<PackageReference Include="Microsoft.Extensions.Http" />
		<PackageReference Include="NSwag.Annotations" />
		<PackageReference Include="Serilog.AspNetCore" />
		<PackageReference Include="Unicode.net" />
		<PackageReference Include="Azure.Storage.Blobs" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Core\GrillBot.Core\GrillBot.Core.csproj" />
		<ProjectReference Include="..\..\Core\GrillBot.Core.HealthCheck\GrillBot.Core.HealthCheck.csproj" />
		<ProjectReference Include="..\..\Core\GrillBot.Core.Metrics\GrillBot.Core.Metrics.csproj" />
		<ProjectReference Include="..\..\Core\GrillBot.Core.RabbitMQ.V2\GrillBot.Core.RabbitMQ.V2.csproj" />
		<ProjectReference Include="..\..\Core\GrillBot.Core.Redis\GrillBot.Core.Redis.csproj" />
		<ProjectReference Include="..\..\Core\GrillBot.Core.Services\GrillBot.Core.Services.csproj" />
	</ItemGroup>

</Project>
