<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Authors>GrillBot</Authors>
        <Description>Core library for healthchecks.</Description>
        <Copyright>All rights reserved</Copyright>
        <PackageProjectUrl>https://grillbot.eu/</PackageProjectUrl>
        <RepositoryUrl>https://github.com/GrillBot/GrillBot.Core</RepositoryUrl>
        <RepositoryType>GitHub</RepositoryType>
        <Version>1.2.1</Version>
        <CopyDebugSymbolFilesFromPackages>true</CopyDebugSymbolFilesFromPackages>
        <CopyDocumentationFilesFromPackages>true</CopyDocumentationFilesFromPackages>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="9.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\GrillBot.Core\GrillBot.Core.csproj" />
    </ItemGroup>

</Project>
