<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
      <NoWarn>1701;1702;IDE0079</NoWarn>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
      <NoWarn>1701;1702;IDE0079</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Polly" />
        <PackageReference Include="RabbitMQ.Client" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\GrillBot.Core.Metrics\GrillBot.Core.Metrics.csproj" />
        <ProjectReference Include="..\GrillBot.Core\GrillBot.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="GrillBot.Core.RabbitMQ.V2.Tests" />
    </ItemGroup>

</Project>
