<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="Discord.Net.Core" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" />
    </ItemGroup>

</Project>
