<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="9.0.0" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
		<PackageReference Include="Discord.Net" Version="3.18.0" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.0.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Core\GrillBot.Core\GrillBot.Core.csproj" />
		<ProjectReference Include="..\..\Core\GrillBot.Core.HealthCheck\GrillBot.Core.HealthCheck.csproj" />
		<ProjectReference Include="..\..\Core\GrillBot.Core.Metrics\GrillBot.Core.Metrics.csproj" />
		<ProjectReference Include="..\..\Core\GrillBot.Core.RabbitMQ.V2\GrillBot.Core.RabbitMQ.V2.csproj" />
		<ProjectReference Include="..\..\Core\GrillBot.Core.Redis\GrillBot.Core.Redis.csproj" />
		<ProjectReference Include="..\..\Core\GrillBot.Core.Services\GrillBot.Core.Services.csproj" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

</Project>
