<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
		<PackageReference Include="AspNetCore.HealthChecks.NpgSql" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
		<PackageReference Include="Discord.Net" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" />
		<PackageReference Include="Swashbuckle.AspNetCore" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\Core\GrillBot.Core\GrillBot.Core.csproj" />
		<ProjectReference Include="..\..\Core\GrillBot.Core.HealthCheck\GrillBot.Core.HealthCheck.csproj" />
		<ProjectReference Include="..\..\Core\GrillBot.Core.Metrics\GrillBot.Core.Metrics.csproj" />
		<ProjectReference Include="..\..\Core\GrillBot.Core.RabbitMQ.V2\GrillBot.Core.RabbitMQ.V2.csproj" />
		<ProjectReference Include="..\..\Core\GrillBot.Core.Redis\GrillBot.Core.Redis.csproj" />
		<ProjectReference Include="..\..\Core\GrillBot.Core.Services\GrillBot.Core.Services.csproj" />
	</ItemGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
	</ItemGroup>

</Project>
