// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UserManagementService.Core.Entity;

#nullable disable

namespace UserManagementService.Core.Migrations
{
    [DbContext(typeof(UserManagementContext))]
    [Migration("20250612183001_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UserManagementService.Core.Entity.GuildUser", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric");

                    b.Property<string>("CurrentNickname")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("GuildId", "UserId");

                    b.ToTable("GuildUsers");
                });

            modelBuilder.Entity("UserManagementService.Core.Entity.GuildUserNickname", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("InsertedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.ToTable("Nicknames");
                });
#pragma warning restore 612, 618
        }
    }
}
