// <auto-generated />
using System;
using AuditLogService.Core.Entity.Statistics;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuditLogService.Core.Migrations.Statistics
{
    [DbContext(typeof(AuditLogStatisticsContext))]
    [Migration("20230713193257_AuditLogStatistics")]
    partial class AuditLogStatistics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("statistics")
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuditLogService.Core.Entity.Statistics.ApiDateCountStatistic", b =>
                {
                    b.Property<string>("ApiGroup")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<long>("Count")
                        .HasColumnType("bigint");

                    b.HasKey("ApiGroup", "Date");

                    b.ToTable("DateCountStatistics", "statistics");
                });

            modelBuilder.Entity("AuditLogService.Core.Entity.Statistics.ApiRequestStat", b =>
                {
                    b.Property<string>("Endpoint")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<long>("FailedCount")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("LastRequest")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LastRunDuration")
                        .HasColumnType("bigint");

                    b.Property<long>("MaxDuration")
                        .HasColumnType("bigint");

                    b.Property<long>("MinDuration")
                        .HasColumnType("bigint");

                    b.Property<long>("SuccessCount")
                        .HasColumnType("bigint");

                    b.Property<long>("TotalDuration")
                        .HasColumnType("bigint");

                    b.HasKey("Endpoint");

                    b.ToTable("RequestStats", "statistics");
                });

            modelBuilder.Entity("AuditLogService.Core.Entity.Statistics.ApiResultCountStatistic", b =>
                {
                    b.Property<string>("ApiGroup")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("Result")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("Count")
                        .HasColumnType("bigint");

                    b.HasKey("ApiGroup", "Result");

                    b.ToTable("ResultCountStatistic", "statistics");
                });
#pragma warning restore 612, 618
        }
    }
}
