// <auto-generated />
using System;
using MessageService.Core.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MessageService.Core.Migrations
{
    [DbContext(typeof(MessageContext))]
    [Migration("20250616214524_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MessageService.Core.Entity.AutoReplyDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCaseSensitive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Reply")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AutoReplyDefinitions");
                });

            modelBuilder.Entity("MessageService.Core.Entity.GuildChannel", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ChannelId")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsAutoReplyDisabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPointsDisabled")
                        .HasColumnType("boolean");

                    b.HasKey("GuildId", "ChannelId");

                    b.ToTable("GuildChannels");
                });
#pragma warning restore 612, 618
        }
    }
}
